version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: architecture-serverless
      buildspec: buildspec-cdk-app.yml
      env:
        variables:
          BUILD_ID: architecture-serverless
          BUILD_BASE_APP: architectures/serverless/app
          BUILD_BASE_INFRA: architectures/serverless/infra
      ignore-failure: true
    - identifier: architecture-container
      buildspec: buildspec-cdk-app.yml
      env:
        variables:
          BUILD_ID: architecture-serverless
          BUILD_BASE_APP: architectures/container/app
          BUILD_BASE_INFRA: architectures/container/infra/2-table
      ignore-failure: true
