# https://taskfile.dev

version: '3'

vars:
  version: v2.0.0-rc.23
  constructs: v10.0.5


env:
  AWS_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_ACCOUNT: 
    sh: aws sts get-caller-identity --query Account --output text

includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app

tasks:

  update:
    dir: infra
    desc: install latest cdk and other modules
    cmds:
      - go get -d github.com/aws/aws-cdk-go/awscdk/v2@{{.version}}
      - go get -d github.com/aws/constructs-go/constructs/v10@{{.constructs}}

  diff:
    dir: infra
    desc: Show stack differences
    cmds:
      - npx cdk@{{.version}} diff
    
  deploy:
    dir: infra
    desc: deploy stack without asking
    deps: [app:build]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - npx {{.npxoptions}} cdk@{{.version}}  deploy  --require-approval never --profile $AWSUME_PROFILE

  destroy:
    dir: infra
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      -  npx cdk@{{.version}}  destroy --force --profile $AWSUME_PROFILE